name: Music Vis MQP Frontend
run-name: ${{ github.actor }} is hosting frontend
on: [push]
jobs:
  Clone-Install-Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: npm install
      - run: npm install -g @angular/cli
      - run: ls -a
      - run: ng build --prod
      - run: ls -a
      - 

      

